const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const cloudinary = require('cloudinary').v2;
const multer = require('multer');
const Donor = require('../models/Donor');
const { protect, hospitalOnly } = require('../middleware/auth');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const storage = multer.memoryStorage();
const upload = multer({ storage, limits: { fileSize: 5 * 1024 * 1024 } });

// Generate PDF certificate for a donor donation
router.post('/generate/:donorId', protect, hospitalOnly, async (req, res) => {
  try {
    const donor = await Donor.findById(req.params.donorId);
    if (!donor) return res.status(404).json({ message: 'Donor not found' });

    const { donationDate, hospitalName } = req.body;

    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', async () => {
      const pdfBuffer = Buffer.concat(buffers);

      // Upload to Cloudinary
      const uploadResult = await new Promise((resolve, reject) => {
        const uploadStream = cloudinary.uploader.upload_stream(
          { resource_type: 'raw', folder: 'bloodlink-certificates', public_id: `cert_${donor._id}_${Date.now()}` },
          (err, result) => {
            if (err) {
              console.error('Cloudinary Generation Error:', err);
              reject(err);
            } else resolve(result);
          }
        );
        uploadStream.end(pdfBuffer);
      });

      // Save cert URL to donor
      await Donor.findByIdAndUpdate(req.params.donorId, {
        $push: {
          donationHistory: {
            date: donationDate || new Date(),
            hospitalName: hospitalName || req.user.name,
            certificateUrl: uploadResult.secure_url,
            registeredByType: req.user.type
          }
        },
      });

      res.json({ certificateUrl: uploadResult.secure_url, message: 'Certificate generated successfully' });
    });

    // PDF Design
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#fff5f5');
    doc.fill('#cc0000').fontSize(28).font('Helvetica-Bold').text('BloodLink', { align: 'center' });
    doc.moveDown(0.3);
    doc.fill('#333').fontSize(18).font('Helvetica').text('Blood Donation Certificate', { align: 'center' });
    doc.moveDown(1);
    doc.strokeColor('#cc0000').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);
    doc.fill('#111').fontSize(14).font('Helvetica').text(`This is to certify that`, { align: 'center' });
    doc.moveDown(0.5);
    doc.fill('#cc0000').fontSize(22).font('Helvetica-Bold').text(donor.name, { align: 'center' });
    doc.moveDown(0.5);
    doc.fill('#111').fontSize(14).font('Helvetica').text(`Blood Group: ${donor.bloodGroup}`, { align: 'center' });
    doc.moveDown(0.5);
    doc.text(`has successfully donated blood on ${new Date(donationDate || Date.now()).toDateString()}`, { align: 'center' });
    doc.moveDown(0.3);
    doc.text(`at ${hospitalName || req.user.name}`, { align: 'center' });
    doc.moveDown(2);
    doc.strokeColor('#cc0000').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);
    doc.fill('#666').fontSize(10).text('Thank you for saving a life. Your contribution matters.', { align: 'center' });
    doc.text(`Certificate generated by BloodLink on ${new Date().toDateString()}`, { align: 'center' });
    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Upload existing certificate (scan/photo)
router.post('/upload/:donorId', protect, hospitalOnly, upload.single('certificate'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ message: 'No file uploaded' });
    const donor = await Donor.findById(req.params.donorId);
    if (!donor) return res.status(404).json({ message: 'Donor not found' });

    const uploadResult = await new Promise((resolve, reject) => {
      const uploadStream = cloudinary.uploader.upload_stream(
        { folder: 'bloodlink-certificates', resource_type: 'auto' },
        (err, result) => { 
          if (err) {
            console.error('Cloudinary Upload Error:', err);
            reject(err);
          } else resolve(result); 
        }
      );
      uploadStream.end(req.file.buffer);
    });

    await Donor.findByIdAndUpdate(req.params.donorId, {
      $push: { donationHistory: { date: new Date(), hospitalName: req.user.name, certificateUrl: uploadResult.secure_url, registeredByType: req.user.type } },
    });

    res.json({ certificateUrl: uploadResult.secure_url });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Donor downloads their own certificate
router.get('/my', protect, async (req, res) => {
  try {
    if (req.userType !== 'donor') return res.status(403).json({ message: 'Donor only' });
    const donor = await Donor.findById(req.userId).select('donationHistory name bloodGroup');
    res.json(donor?.donationHistory || []);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
